# Generated by Django 6.0.6 on 2026-07-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_changed_username',
            field=models.BooleanField(default=False),
        ),
    ]
