# Generated by Django 6.0.6 on 2026-06-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_coupon_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='return_type',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('expired', 'Expired'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
