# Generated by Django 6.0.6 on 2026-07-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_payment_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
