# Generated by Django 6.0.6 on 2026-07-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='refund_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
